const { Router } = require('express');
const c = require('../controllers/authController');
const authMw = require('../middleware/auth');
const rbac = require('../middleware/rbac');
const tenantScope = require('../middleware/tenantScope');
const { loginLimiter, registerLimiter } = require('../middleware/rateLimiter');

const r = Router();
r.post('/register', registerLimiter, c.register);
r.get('/verify-email', c.verifyEmail);
r.post('/login', loginLimiter, c.login);
r.post('/refresh', c.refresh);
r.post('/logout', authMw, c.logout);
r.post('/forgot-password', c.forgotPassword);
r.post('/reset-password', c.resetPassword);
r.post('/invite', authMw, tenantScope, rbac('ADMIN', 'MANAGER'), c.inviteStaff);
r.post('/accept-invite', c.acceptInvite);
r.get('/accept-invite', c.acceptInviteForm);  
r.post('/accept-invite', c.acceptInvite);
module.exports = r;
